import type { LevelDef } from "./types";

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: "初入牧场",
    hint: "点没有被压住的牌，三个相同就会消除。",
    types: 3,
    cols: 4,
    rows: 3,
    layers: 2,
    ease: 0.9,
    undo: 3,
    shuffle: 2,
    remove: 2,
    layout: "grid",
  },
  {
    id: 2,
    name: "青草堆",
    hint: "上层会挡住下层。先拆开的牌。",
    types: 4,
    cols: 5,
    rows: 4,
    layers: 3,
    ease: 0.75,
    undo: 3,
    shuffle: 2,
    remove: 2,
    layout: "inset",
  },
  {
    id: 3,
    name: "羊毛垛",
    hint: "槽位只有 7 格，满了就失败。",
    types: 5,
    cols: 5,
    rows: 4,
    layers: 4,
    ease: 0.62,
    undo: 2,
    shuffle: 2,
    remove: 2,
    layout: "plus",
  },
  {
    id: 4,
    name: "丰收季",
    hint: "撤回、洗牌、移出能帮你解围。",
    types: 6,
    cols: 6,
    rows: 5,
    layers: 4,
    ease: 0.5,
    undo: 2,
    shuffle: 2,
    remove: 1,
    layout: "inset",
  },
  {
    id: 5,
    name: "迷雾羊圈",
    hint: "同种牌会尽量挤在一起，方便三消。",
    types: 7,
    cols: 6,
    rows: 5,
    layers: 5,
    ease: 0.42,
    undo: 2,
    shuffle: 1,
    remove: 1,
    layout: "diamond",
  },
  {
    id: 6,
    name: "层层叠叠",
    hint: "先清边上露出的牌，再挖中间。",
    types: 8,
    cols: 7,
    rows: 6,
    layers: 5,
    ease: 0.34,
    undo: 2,
    shuffle: 1,
    remove: 1,
    layout: "piles",
  },
  {
    id: 7,
    name: "羊村集市",
    hint: "种类变多了，槽位更要精打细算。",
    types: 10,
    cols: 7,
    rows: 6,
    layers: 6,
    ease: 0.28,
    undo: 1,
    shuffle: 1,
    remove: 1,
    layout: "plus",
  },
  {
    id: 8,
    name: "终极牧场",
    hint: "这关很密。卡住就洗牌。",
    types: 12,
    cols: 8,
    rows: 6,
    layers: 6,
    ease: 0.22,
    undo: 1,
    shuffle: 1,
    remove: 1,
    layout: "piles",
  },
];

export function getLevel(id: number): LevelDef {
  const named = LEVELS.find((l) => l.id === id);
  if (named) return named;
  const extra = id - LEVELS.length;
  const types = Math.min(16, 8 + extra);
  return {
    id,
    name: `无尽牧场 ${extra}`,
    hint: "层数和种类会继续往上加。",
    types,
    cols: Math.min(8, 6 + Math.floor(extra / 2)),
    rows: Math.min(7, 5 + Math.floor(extra / 3)),
    layers: Math.min(8, 5 + Math.floor(extra / 2)),
    ease: Math.max(0.12, 0.28 - extra * 0.02),
    undo: extra % 2 === 0 ? 2 : 1,
    shuffle: 1,
    remove: extra % 3 === 0 ? 2 : 1,
    layout: extra % 2 === 0 ? "piles" : "inset",
  };
}
